#+TITLE: Automated Testing of Vlabs Landing Pages
#+AUTHOR: VLEAD
#+DATE: [2017-05-03 Wednesday]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ./org-templates/level-0.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate


* Introduction 
  This document describes the automation testing done using
  selenium on  =vlabs-landing-pages=.


* Installation of Selenium IDE
** Pre-requisites
   1) Operating System: Ubuntu 14.04
   2) Firefox Version: 40.0.3 
     
** Steps
  Follow the below steps to install selenium IDE
  1) Add Selenium IDE to the firefox web browser as a
     plugin. Visit [[https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/][link]] and click on =Add to Firefox= button
     to add Selenium IDE to firefox.
  2) Restart your browser to apply changes.
  3) =Selenium= Icon will be shown in the browser top corner.
    
* Procedure
  This automated testing is done for one Lab 
** Test Login/Logout
  Follow the below instructions to test =Login/Logout= 
  1) Click on =selenium= icon in the firefox browser
  2) Enter the =url= in the =Base URL= section in =selenium
     RC= window as follows
     #+BEGIN_EXAMPLE
     http://mybox.vlabs.ac.in
     #+END_EXAMPLE
  3) Click on the =record= button which is =red= in color
  4) Visit the browser and login. The following table will
     be generated in =selenium RC=. 
     |--------------+------------------------+-------------------|
     | command      | Target                 | Value             |
     |--------------+------------------------+-------------------|
     | open         | /logout                |                   |
     |--------------+------------------------+-------------------|
     | open         | /login                 |                   |
     |--------------+------------------------+-------------------|
     | type         | id=login-email         | honor@example.com |
     |--------------+------------------------+-------------------|
     | type         | id=login-password      | edx               |
     |--------------+------------------------+-------------------|
     | clickAndWait | button[@type='submit'] |                   |
     |--------------+------------------------+-------------------| 
  5) The source code for the above testing will be generated
     as follows:
     #+BEGIN_EXAMPLE
     <?xml version="1.0" encoding="UTF-8"?>
     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
     <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
     <head profile="http://selenium-ide.openqa.org/profiles/test-case">
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
     <link rel="selenium.base" href="http://mybox.vlabs.ac.in/login" />
     <title>New Test</title>
     </head>
     <body>
     <table cellpadding="1" cellspacing="1" border="1">
     <thead>
     <tr><td rowspan="1" colspan="3">New Test</td></tr>
     </thead><tbody>
     <tr>
     <td>open</td>
     <td>/logout</td>
     <td></td>
     </tr>
     <tr>
     <td>open</td>
     <td>/login</td>
     <td></td>
     </tr>
     <tr>
     <td>type</td>
     <td>id=login-email</td>
     <td>honor@example.com</td>
     </tr>
     <tr>
     <td>type</td>
     <td>id=login-password</td>
     <td>edx</td>
     </tr>
     <tr>
     <td>clickAndWait</td>
     <td>//button[@type='submit']</td>
     <td></td>
     </tr>
     
     </tbody></table>
     </body>
     </html>
     #+END_EXAMPLE
     
** Test Lab URL is working 
  Follow the below instructions to test =Virtual Proteomics
  Lab= 
  1) Steps 1, 2, and 3 is same as mentioned in the above
     test case.
  2) Visit the browser and access the =Virtual Proteomics
     Lab= lab. The following table will be generated in
     =selenium RC=.
     |--------------+----------------------------------------------------------------------------+-------------------|
     | command      | Target                                                                     | Value             |
     |--------------+----------------------------------------------------------------------------+-------------------|
     | open         | /                                                                          |                   |
     |--------------+----------------------------------------------------------------------------+-------------------|
     | clickAndWait | //article[@id='course-v1:Virtual-Labs+biotech25+Anytime']/a/header/div/div |                   |
     |--------------+----------------------------------------------------------------------------+-------------------|
     | clickAndWait | link=Enroll in biotech25                                                   |                   |
     |--------------+----------------------------------------------------------------------------+-------------------|
     | click        | link=Sign in.                                                              |                   |
     |--------------+----------------------------------------------------------------------------+-------------------|
     | type         | id=login-email                                                             | honor@example.com |
     |--------------+----------------------------------------------------------------------------+-------------------|
     | type         | id=login-password                                                          | edx               |
     |--------------+----------------------------------------------------------------------------+-------------------|
     | clickAndWait | //button[@type='submit']                                                   |                   |
     |--------------+----------------------------------------------------------------------------+-------------------|

  3) The source code for the above testing will be generated
     as follows:
     #+BEGIN_SRC html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head profile="http://selenium-ide.openqa.org/profiles/test-case">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="selenium.base" href="http://mybox.vlabs.ac.in/" />
    <title>New Test</title>
  </head>
  <body>
    <table cellpadding="1" cellspacing="1" border="1">
      <thead>
        <tr><td rowspan="1" colspan="3">New Test</td></tr>
      </<th></th>ead><tbody>
        <tr>
          <td>open</td>
          <td>/</td>
          <td></td>
        </tr>
        <tr>
          <td>clickAndWait</td>
          <td>//article[@id='course-v1:Virtual-Labs+biotech25+Anytime']/a/header/div/div</td>
          <td></<td></td>>
        </tr>
        <tr>
          <td>clickAndWait</td>
          <td>link=Enroll in biotech25</td>
          <td></td>
        </tr>
        <tr>
          <td>click</td>
          <td>link=Sign in.</td>
          <td></td>
        </tr>
        <tr>
          <td>type</td>
          <td>id=login-email</td>
          <td>honor@example.com</td>
        </tr>
        <tr>
          <td>type</td>
          <td>id=login-password</td>
          <td>edx</td>
        </tr>
        <tr>
          <td>clickAndWait</td>
          <td>//button[@type='submit']</td>
          <td></td>
        </tr>
        
    </tbody></table>
  </body>
</html>

#+END_SRC

  4) Similarly to test all others labs, update the lab_id in the table
     format (or) in the script and run tests.
     
** Test Experiment, Full Screen and Feedbacks are working 
  Follow the below instructions to test =FAB Laboratory= 
  1) Steps 1, 2, and 3 is same as mentioned in the above
     test case.
  2) Visit  the browser  and  access  the experiments  and
     feedbacks of  =FAB Laboratory= lab. The  auto generated
     source code  will be visible  in the form of  table and
     xml code in =selenium RC=.
  3) The source code for the above testing will be generated
     as follows:
     #+BEGIN_SRC html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://mybox.vlabs.ac.in/" />
<title>New Test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/dashboard</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=FAB Laboratory</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Course</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@ddd96c36679942f1bd2e9201193397a2']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>//button[@onclick='popup()']</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Simulator</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@19f35668f90047bb8da2c698443bb259']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Feedback</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@06c44f66f7bc41a2b5d4460c2bc4bbab']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=p &gt; button</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Simulator</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@9344ce21aefb441494113c724c72e1c1']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Feedback</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@2411918b64274853b65cc3d60ee22f95']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=p &gt; button</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Simulator</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@64d53cb788cc4bad96c7f00ac27196cc']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Feedback</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@a54182829b5c4aaba2a7b2f78a34437e']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=p &gt; button</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Simulator</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@648401f06d8745d7821bf5a7b45e8c58']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Feedback</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@47cfc4fbc4e14fc8ba8a5e86c5b20c30']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=p &gt; button</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Simulator</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@b23c01e2244d477aa330e4c237c4fb07']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Feedback</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@fb43e0a078b24acfa4646ecdd637c965']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=p &gt; button</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Simulator</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@52d56932c5fb43d3a2c6fc6b938ee18a']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Feedback</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@6ed5d60b0f9640e791190eb31c69c89b']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Feedback</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@c9bca2067d07463caa20f30cf8530c3c']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Feedback</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@5a8995f45c9a4d0a91e7262fe6bec272']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Course</td>
	<td></td>
</tr>

</tbody></table>
</body>
</html>

     #+END_SRC
  4) Similarly Repeat the same test case for all others labs.
     
** Test Visit, Fill up and Submit Experiment Feedback Form 
  Follow the below instructions to test experiment feedback
  of =FAB Laboratory= 
  1) Steps 1, 2, and 3 is same as mentioned in the above
     test case.
  2) Visit the browser and access the Feedback section of
     experiment =Computer Controlled Cutting of wooden= of
     =FAB Laboratory= lab. The auto generated source code
     will be visible in the form of table and xml code in
     =selenium RC=.

#+BEGIN_EXAMPLE
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://mybox.vlabs.ac.in/" />
<title>New Test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/dashboard</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=FAB Laboratory</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>link=Course</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>//a[@id='block-v1:Virtual-Labs+mech18+Anytime+type@sequential+block@19f35668f90047bb8da2c698443bb259']/div/span</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=Click here</td>
	<td></td>
</tr>
<tr>
	<td>waitForPopUp</td>
	<td>_blank</td>
	<td>30000</td>
</tr>
<tr>
	<td>selectWindow</td>
	<td>title=Feedback Portal</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>xpath=(//input[@name='Did you attempt the experiment?'])[2]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>xpath=(//input[@name='How much did you know about the experiment before doing it in Virtual Labs?'])[8]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>xpath=(//input[@name='Is this experiment part of your curriculum?'])[4]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>xpath=(//input[@name='Will you recommend this experiment to others?'])[10]</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=9</td>
	<td>test</td>
</tr>
<tr>
	<td>click</td>
	<td>css=button.btn.btn-primary</td>
	<td></td>
</tr>

</tbody></table>
</body>
</html>

#+END_EXAMPLE

